### ISSUE TITLE
开机引导只有win10一个选项

### ISSUE THREAD

**Issue by jasonziai** [fnoopv/MSI-Z390-Gaming-Edge-AC_OC#2]
配置基本相同，9600kf+同主板+5700刷xt固件。用了你的efi开机引导只有一个win10。

**Comment by fnoopv** [comment]
BIOS设置好了吗？硬盘引导项设置的第一位的是mac所在的盘吗？

**Comment by jasonziai** [comment]
> BIOS设置好了吗？硬盘引导项设置的第一位的是mac所在的盘吗？

太强了兄弟，已经弄好了。我百毒了一下，把硬盘扫描scan。。。还原为0就扫描到了。再次感谢！！！我现在就是显卡dp输出声音到显示器不能调音量，其余真的舒服。
