### ISSUE TITLE
求助安装Big Sur失败的问题

### ISSUE THREAD

**Issue by Rorschachina** [fnoopv/MSI-Z390-Gaming-Edge-AC_OC#5]
本人配置跟楼主差不多，不过我是不带核显的9600KF，显卡是RX 590，我按照黑果小兵教程里设置了BIOS，但是安装big sur的时候总是卡在第二次重启，跑码会卡住，Google了错误码也一直没能解决问题，不知道是我BIOS设置的问题还是说OC配置不对，我安装的时候是用的黑果小兵的镜像，没有改任何东西，安装一直不成功。。。我是双系统，macos和win10是同一个硬盘装的，不知道这个有无影响，我big sur之前的版本都可以正常安装，就是big sur不行

**Comment by fnoopv** [comment]
没有全新安装过Big sur，我是直接10.15.7升级上来的，建议按照[这个教程](https://blog.xjn819.com/post/opencore-guide.html)来配OC

**Comment by DDD-Rock** [comment]
我已经安完了，反馈一下这个问题，全新安装第一次重启卡住，百度解决了。第二次重启卡住，翻遍百度谷歌没见到什么好办法，后来装10.15.7之后再升级，曲线救国，现在一切OK
