### ISSUE TITLE
升级big sur以后黑屏

### ISSUE THREAD

**Issue by jasonziai** [fnoopv/MSI-Z390-Gaming-Edge-AC_OC#7]
紧跟大佬步伐，一路升级到最新big sur，也正常用几次。昨天开机就不对了，读条到1/3时就黑屏了，显示器无信号，几秒后显示器亮了，但是屏幕全黑，按电源键可正常休眠。打开-v不会卡还是启动到这样的状态。完全无从下手了。。。

**Comment by fnoopv** [comment]
-v 最后输出什么？

**Comment by jasonziai** [comment]
更新了64还是黑。。。

**Comment by jasonziai** [comment]
最后一行
IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0,  sm 0x0

**Comment by jasonziai** [comment]
搜索了一通，感觉应该是9600kf没有核显的原因。可是在DeviceProperties里删除了核显的那段信息，还是黑屏。。。是不是还有地方是关于核显的。

**Comment by fnoopv** [comment]
你AAPL,ig-platform-id改了吗

**Comment by jasonziai** [comment]
没核显AAPL,ig-platform-id里应该改成什么？我百度谷歌找不到，就直接把DeviceProperties里的AAPL,ig-platform-id这个字段删除了。结果还是一样。
